// eslint-disable-next-line no-unused-vars
export const productsList = [
  {
    id: 1,
    category: 2,
    cart: 0,
    name: "Ecran",
    description: "une description",
    price: 85.32,
    stock: 20,
    image: "image1.png",
  },
  {
    id: 2,
    category: 2,
    cart: 0,
    name: "Pc Portable",
    description: "une description",
    price: 542.54,
    stock: 10,
    image: "image2.png",
  },
  {
    id: 3,
    category: 2,
    cart: 0,
    name: "Disque SSD",
    description: "une description",
    price: 150.41,
    stock: 52,
    image: "image3.png",
  },
  {
    id: 4,
    category: 1,
    cart: 0,
    name: "Biscuits",
    description: "une description",
    price: 2.45,
    stock: 0,
    image: "image4.png",
  },
  {
    id: 5,
    category: 2,
    cart: 0,
    name: "Smartphone",
    description: "une description",
    price: 324.0,
    stock: 0,
    image: "image5.png",
  },
];
